package model.siemens;

public enum SimpleSiemensType {

	BOOL, INT, DINT, REAL, BYTE, DWORD, WORD, IEC_TIMER, STRING, CHAR, DATE, DATEANDTIME, LINT, LREAL, LTIME, LWORD, S5TIME, SINT, TIME, TIMEOFDAY, UDINT, UINT, ULINT, USINT
}
